### PR TITLE
Configuration feature

### PR DESCRIPTION
**Pull request by ezh**
I copy an ability to read configuration file from ptpython. It is pain for me to work with hardcoded values.

I like #6, but you don't want to merge it. I suspect that we may create a pack of configuration recipes for other users with effective debugging tips. Use IPython as cli from #6 is example one.

### CODE REVIEW

**Comment by ezh** [comment]
Right now I am already add custom commands to ptpdb. It is as simple as

```python
    def do_test(user_input):
        debugger.message("123")
    debugger.do_test = do_test
    debugger.commands_with_help['test'] = "Test command"
```
I suspect that an easy customization is key feature of all software like this.  :smirk:
But I prefer to create simple pull request that is easy to review. This will be my second pull request if you accept this feature.

**Comment by ezh** [comment]
ping @jonathanslenders Please give me a second.  Tell if you don't accept any pull requests. I will understand.

**Comment by jonathanslenders** [comment]
Hi @ezh,
Sorry for the late reply. I had a few remarks, but then I'll merge it.

**Comment by ezh** [comment]
Sure. Thanks for the reply.

**Comment by bitterjug** [comment]
+1 I'd love to be able to start ptpdb in vim mode and with code colours I can read.

**Comment by dakra** [comment]
+1
I would like to start ptpdb with my own config as well :)

**Pull request closed without merging**
